const API_URL="https://script.google.com/macros/s/AKfycbwcLGd8IKvi5BSmXZoRD41rqctR7wIVbZDbK2uzcPwwjV7giXkqiaFAKqNuqsQgBd_r/exec";let data=null,charts={};
const $=id=>document.getElementById(id),M=x=>"₹"+(Number(x)||0).toLocaleString("en-IN",{maximumFractionDigits:0}),E=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(action,params={}){let u=new URL(API_URL);u.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>{if(v&&v!=="ALL")u.searchParams.set(k,v)});let r=await fetch(u);if(!r.ok)throw Error("API "+r.status);let j=await r.json();if(!j.ok)throw Error(j.error||"API error");return j}
function opts(id,a){$(id).innerHTML='<option>ALL</option>'+a.map(x=>`<option>${E(x)}</option>`).join("")}
function chart(id,type,labels,values){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label:"Sales",data:values,borderWidth:1}]},options:{responsive:true,maintainAspectRatio:false}})}
async function loadLists(){let j=await api("lists");opts("sh",j.sh);opts("party",j.party);opts("state",j.state);opts("group",j.group);opts("fy",j.fy);opts("month",j.month)}
function params(){return {sh:$("sh").value,state:$("state").value,group:$("group").value,fy:$("fy").value,month:$("month").value,party:$("party").value}}
async function load(){ $("status").textContent="Loading…";try{data=await api("summary",params());$("errorBox").classList.add("hide");let k=data.kpi;Object.keys(k).forEach(x=>{if($(x))$(x).textContent=M(k[x])});render(data);$("status").textContent="● LIVE DATA";}catch(e){$("status").textContent="API connection error";$("errorBox").classList.remove("hide");$("errorBox").innerHTML="API connection failed: "+E(e.message)+" &nbsp; <button onclick='load()'>Retry</button>";console.error(e)}}
function render(d){chart("heads","bar",Object.keys(d.heads).slice(0,15),Object.values(d.heads).slice(0,15));chart("states","bar",Object.keys(d.states).slice(0,15),Object.values(d.states).slice(0,15));chart("groups","doughnut",Object.keys(d.groups).slice(0,12),Object.values(d.groups).slice(0,12));chart("months","bar",Object.keys(d.months),Object.values(d.months));$("partyRows").innerHTML=d.party.map(x=>`<tr><td class="link" onclick='party(${JSON.stringify(x.party)})'>${E(x.party)}</td><td>${E(x.sh)}</td><td>${E(x.state)}</td><td>${M(x.sales)}</td><td>${M(x.payment)}</td><td><b>${M(x.outstanding)}</b></td></tr>`).join("")}
async function party(p){$("mt").textContent=p;$("mb").innerHTML="Loading party details…";$("modal").classList.remove("hide");let j=await api("party",{party:p});$("mb").innerHTML=`<table><thead><tr><th>Date</th><th>Invoice</th><th>Item Code</th><th>Group</th><th>Qty</th><th>Rate</th><th>Taxable</th><th>Total</th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${E(x.date)}</td><td class="link" onclick='invoice(${JSON.stringify(x.invoice)},${JSON.stringify(p)})'>${E(x.invoice)}</td><td>${E(x.code)}</td><td>${E(x.group)}</td><td>${x.qty}</td><td>${M(x.rate)}</td><td>${M(x.taxable)}</td><td>${M(x.total)}</td></tr>`).join("")}</tbody></table>`}
async function invoice(inv,p){$("mt").textContent="Invoice "+inv;$("mb").innerHTML="Loading invoice…";let j=await api("invoice",{party:p,invoice:inv});$("mb").innerHTML=`<h3>${E(p)}</h3><table><thead><tr><th>Date</th><th>Item Code</th><th>Group</th><th>Qty</th><th>Sale Rate</th><th>Taxable</th><th>GST 18%</th><th>Total</th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${E(x.date)}</td><td>${E(x.code)}</td><td>${E(x.group)}</td><td>${x.qty}</td><td>${M(x.rate)}</td><td>${M(x.taxable)}</td><td>${M(x.gst)}</td><td>${M(x.total)}</td></tr>`).join("")}</tbody></table>`}
$("apply").onclick=load;$("close").onclick=()=>$("modal").classList.add("hide");$("modal").onclick=e=>{if(e.target.id==="modal")$("modal").classList.add("hide")};
async function start(){try{await loadLists();await load()}catch(e){$("status").textContent="API connection error";$("errorBox").classList.remove("hide");$("errorBox").textContent="API connection failed: "+e.message;console.error(e)}}
start();
